<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Lance" name="com.biz.wltq.testcase.login.LoginPage_006_Fail_Incorrect_Username_Test" tests="1" failures="1" timestamp="22 Apr 2016 08:08:56 GMT" time="0.408" errors="0">
  <testcase name="loginFailTest_incorrectUsername" time="0.408" classname="com.biz.wltq.testcase.login.LoginPage_006_Fail_Incorrect_Username_Test">
    <failure type="java.lang.AssertionError" message="期望的文字是 [用户名或密码错误！] 但是找到了 []">
      <![CDATA[java.lang.AssertionError: 期望的文字是 [用户名或密码错误！] 但是找到了 []
	at org.testng.Assert.fail(Assert.java:94)
	at com.biz.wltq.util.SeleniumUtil.isTextCorrect(SeleniumUtil.java:242)
	at com.biz.wltq.pages.pageshelper.AlertPageHelper.checkAlertInfo(AlertPageHelper.java:20)
	at com.biz.wltq.testcase.login.LoginPage_006_Fail_Incorrect_Username_Test.loginFailTest_incorrectUsername(LoginPage_006_Fail_Incorrect_Username_Test.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- loginFailTest_incorrectUsername -->
</testsuite> <!-- com.biz.wltq.testcase.login.LoginPage_006_Fail_Incorrect_Username_Test -->
